### ISSUE TITLE
Switching Alt and Super Key

### ISSUE THREAD

**Issue by g4challenge** [petrstepanov/gnome-macos-remap#15]
in my case for the keyboard the default install instructions result in the flipped assignment of those two letters.
Can I easily switch from e.g. Super + V to alt +V?

The keyboard used is a Microsoft Sculpt Comfort and Ubuntu 20.04 running X11.

**Comment by petrstepanov** [comment]
Hi, there are a few options to do it:

- You can modify the `/usr/share/X11/xkb/symbols/pc` file. 
- If using GNOME desktop environment, install and open GNOME Tweaks app. Go to "Keyboard & Mouse" > "Additional Layout Options" > "Alt and Win behavior" > "Alt is swapped with Win".
- Finally you can simply use Autokey app to remap a particular combination "Super + V" to "Alt +V".

Hope this helps. Meanwhile I will close this issue because it is not related to the repository purpose.
